default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false  
  pool: 5
  username: postgres
  password: click227
  host: localhost

development:
  <<: *default
  database: redmine

test:
  <<: *default
  database: redmin_test

production:
  <<: *default
  database: redmine_production
